language: php
php:
  - 5.6.40
  - 7.0.33
  - 7.2.14

sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

before_install:
  - composer self-update

install:
  - composer install

script:
  - composer lint
  - composer sniff
